name: PHPUnit

on:
  pull_request:
    branches:
      - develop
      - master
  workflow_dispatch:

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, pdo_mysql, dom, fileinfo, gd, imagick, json, exif
          tools: composer:v2, php-cs-fixer
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-dev
      
      - name: Prepare the application
        run: |
          cp .env.ci.example .env
          php artisan key:generate
      
      - name: Run migrations
        run: php artisan migrate --force
      
      - name: Run tests
        run: vendor/bin/phpunit
